services:

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  api:
    build: .
    image: api:1.0.0
    command: gunicorn myapp.wsgi:application --bind 0.0.0.0:8001 --workers 4 --access-logfile '-'
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16-bookworm
    volumes:
      - data:/var/lib/postgresql/data/
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5430:5432"

volumes:
  data: