# Generated by Django 5.2 on 2025-04-19 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("hotel_room", models.IntegerField(unique=True)),
                ("price", models.IntegerField()),
                ("description", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                (
                    "hotel_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.hotel"
                    ),
                ),
            ],
        ),
    ]
