# Generated by Django 5.2 on 2025-04-19 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_hotel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
