# Generated by Django 5.2 on 2025-04-20 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_hotel_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="hotel_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.hotel",
                to_field="hotel_room",
            ),
        ),
    ]
